# Generated by Django 4.2.7 on 2025-08-18 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('suspicious_login', 'Đăng nhập đáng ngờ'), ('multiple_failed_login', 'Đăng nhập sai nhiều lần'), ('permission_denied', 'Truy cập bị từ chối'), ('data_breach_attempt', 'Cố gắng vi phạm dữ liệu'), ('sql_injection', 'SQL Injection'), ('xss_attempt', 'XSS Attack'), ('brute_force', 'Brute Force Attack'), ('unusual_activity', 'Hoạt động bất thường'), ('other', 'Khác')], max_length=30, verbose_name='Loại sự kiện')),
                ('risk_level', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Nghiêm trọng')], max_length=20, verbose_name='Mức độ rủi ro')),
                ('status', models.CharField(choices=[('detected', 'Phát hiện'), ('investigating', 'Đang điều tra'), ('resolved', 'Đã giải quyết'), ('false_positive', 'Báo động giả')], default='detected', max_length=20, verbose_name='Trạng thái')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('source_ip', models.GenericIPAddressField(verbose_name='IP nguồn')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu request')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, verbose_name='Referer')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Ghi chú giải quyết')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian phát hiện')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giải quyết')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_events', to=settings.AUTH_USER_MODEL, verbose_name='Người điều tra')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng liên quan')),
            ],
            options={
                'verbose_name': 'Sự kiện bảo mật',
                'verbose_name_plural': 'Sự kiện bảo mật',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đăng nhập')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đăng xuất')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('session_key', models.CharField(max_length=40, verbose_name='Session Key')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Đăng nhập thành công')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='Lý do thất bại')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử đăng nhập',
                'verbose_name_plural': 'Lịch sử đăng nhập',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='DataExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('xml', 'XML')], max_length=20, verbose_name='Loại file')),
                ('table_name', models.CharField(max_length=100, verbose_name='Bảng dữ liệu')),
                ('record_count', models.PositiveIntegerField(verbose_name='Số bản ghi')),
                ('file_size', models.PositiveIntegerField(verbose_name='Kích thước file (bytes)')),
                ('filters_applied', models.JSONField(blank=True, default=dict, verbose_name='Bộ lọc áp dụng')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Số lần tải')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn file')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Địa chỉ IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hết hạn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người xuất')),
            ],
            options={
                'verbose_name': 'Nhật ký xuất dữ liệu',
                'verbose_name_plural': 'Nhật ký xuất dữ liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa'), ('view', 'Xem'), ('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('export', 'Xuất dữ liệu'), ('import', 'Nhập dữ liệu'), ('approve', 'Duyệt'), ('reject', 'Từ chối'), ('cancel', 'Hủy'), ('restore', 'Khôi phục'), ('other', 'Khác')], max_length=20, verbose_name='Hành động')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('severity', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Nghiêm trọng')], default='low', max_length=20, verbose_name='Mức độ')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Giá trị cũ')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Giá trị mới')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bổ sung')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='activity_lo_user_id_8d9f3d_idx'), models.Index(fields=['action', 'timestamp'], name='activity_lo_action_e13a65_idx'), models.Index(fields=['content_type', 'object_id'], name='activity_lo_content_50462e_idx'), models.Index(fields=['ip_address', 'timestamp'], name='activity_lo_ip_addr_56ce69_idx')],
            },
        ),
    ]
