# Generated by Django 4.2.7 on 2025-08-18 05:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=50, unique=True, verbose_name='Mã thanh toán')),
                ('payment_type', models.CharField(choices=[('inbound', 'Thu tiền (Khách trả)'), ('outbound', 'Chi tiền (Trả nhà cung cấp)')], max_length=20, verbose_name='Loại thanh toán')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('check', 'Séc'), ('credit_card', 'Thẻ tín dụng'), ('letter_of_credit', 'Thư tín dụng (L/C)'), ('other', 'Khác')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_date', models.DateField(verbose_name='Ngày thanh toán')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Ngày đến hạn')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Tên ngân hàng')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Tỷ giá')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Tiền tệ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('customer', models.ForeignKey(blank=True, help_text='Thanh toán từ khách hàng', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Khách hàng')),
                ('farmer', models.ForeignKey(blank=True, help_text='Thanh toán cho nông dân', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer', verbose_name='Nông dân')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('receipt', 'Phiếu thu'), ('payment_voucher', 'Phiếu chi'), ('bank_statement', 'Sao kê ngân hàng'), ('invoice', 'Hóa đơn'), ('contract', 'Hợp đồng'), ('other', 'Khác')], max_length=20, verbose_name='Loại tài liệu')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('file', models.FileField(upload_to='payment_documents/', verbose_name='File')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payments.payment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Tài liệu thanh toán',
                'verbose_name_plural': 'Tài liệu thanh toán',
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='Số thứ tự')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền')),
                ('due_date', models.DateField(verbose_name='Ngày đến hạn')),
                ('description', models.CharField(max_length=200, verbose_name='Mô tả')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='orders.order', verbose_name='Đơn hàng')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment', verbose_name='Thanh toán')),
            ],
            options={
                'verbose_name': 'Lịch thanh toán',
                'verbose_name_plural': 'Lịch thanh toán',
                'ordering': ['order', 'sequence'],
                'unique_together': {('order', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3, verbose_name='Từ tiền tệ')),
                ('to_currency', models.CharField(max_length=3, verbose_name='Sang tiền tệ')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tỷ giá')),
                ('effective_date', models.DateField(verbose_name='Ngày hiệu lực')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Tỷ giá',
                'verbose_name_plural': 'Tỷ giá',
                'ordering': ['-effective_date'],
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
    ]
