# Generated by Django 4.2.7 on 2025-08-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDocument',
        ),
    ]
