# Generated by Django 4.2.7 on 2025-08-18 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bill_of_lading', 'Vận đơn (B/L)'), ('airway_bill', 'Vận đơn hàng không (AWB)'), ('trucking_bill', 'Vận đơn đường bộ'), ('container_list', 'Danh sách container'), ('delivery_order', 'Lệnh giao hàng')], max_length=20, verbose_name='Loại tài liệu')),
                ('document_number', models.CharField(max_length=100, verbose_name='Số tài liệu')),
                ('carrier_name', models.CharField(max_length=200, verbose_name='Hãng vận tải')),
                ('vessel_name', models.CharField(blank=True, max_length=200, verbose_name='Tên tàu/máy bay')),
                ('voyage_number', models.CharField(blank=True, max_length=50, verbose_name='Số chuyến')),
                ('port_of_loading', models.CharField(max_length=200, verbose_name='Cảng xếp hàng')),
                ('port_of_discharge', models.CharField(max_length=200, verbose_name='Cảng dỡ hàng')),
                ('place_of_delivery', models.CharField(blank=True, max_length=200, verbose_name='Nơi giao hàng')),
                ('issue_date', models.DateField(verbose_name='Ngày phát hành')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='Ngày khởi hành dự kiến')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='Ngày đến dự kiến')),
                ('file', models.FileField(upload_to='shipping_documents/', verbose_name='File tài liệu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_documents', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Tài liệu vận chuyển',
                'verbose_name_plural': 'Tài liệu vận chuyển',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportExportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('customs_declaration', 'Tờ khai hải quan'), ('commercial_invoice', 'Hóa đơn thương mại'), ('packing_list', 'Danh sách đóng gói'), ('bill_of_lading', 'Vận đơn'), ('certificate_of_origin', 'Giấy chứng nhận xuất xứ (CO)'), ('quality_certificate', 'Giấy chứng nhận chất lượng (CQ)'), ('phytosanitary_certificate', 'Giấy chứng nhận kiểm dịch thực vật'), ('insurance_certificate', 'Giấy chứng nhận bảo hiểm'), ('letter_of_credit', 'Thư tín dụng'), ('inspection_certificate', 'Giấy chứng nhận kiểm tra'), ('other', 'Khác')], max_length=30, verbose_name='Loại tài liệu')),
                ('document_number', models.CharField(max_length=100, verbose_name='Số tài liệu')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('issue_date', models.DateField(verbose_name='Ngày phát hành')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('issuing_authority', models.CharField(blank=True, max_length=200, verbose_name='Cơ quan cấp')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('submitted', 'Đã nộp'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối'), ('expired', 'Hết hạn')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Ngày nộp')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('file', models.FileField(upload_to='import_export_documents/', verbose_name='File tài liệu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ie_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ie_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_export_documents', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Tài liệu xuất nhập khẩu',
                'verbose_name_plural': 'Tài liệu xuất nhập khẩu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomsDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(max_length=50, unique=True, verbose_name='Số tờ khai')),
                ('declaration_type', models.CharField(choices=[('import', 'Nhập khẩu'), ('export', 'Xuất khẩu')], max_length=20, verbose_name='Loại tờ khai')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('submitted', 'Đã nộp'), ('processing', 'Đang xử lý'), ('cleared', 'Đã thông quan'), ('rejected', 'Bị từ chối')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('customs_office', models.CharField(max_length=200, verbose_name='Cơ quan hải quan')),
                ('port_of_entry', models.CharField(max_length=200, verbose_name='Cửa khẩu')),
                ('declaration_date', models.DateField(verbose_name='Ngày khai báo')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Ngày nộp')),
                ('clearance_date', models.DateField(blank=True, null=True, verbose_name='Ngày thông quan')),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Giá trị khai báo')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Tiền tệ')),
                ('customs_duty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Thuế quan')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Thuế VAT')),
                ('other_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phí khác')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng thuế phí')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customs_declaration', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Tờ khai hải quan',
                'verbose_name_plural': 'Tờ khai hải quan',
                'ordering': ['-created_at'],
            },
        ),
    ]
