# Generated by Django 4.2.7 on 2025-08-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=20, unique=True, verbose_name='Mã khách hàng')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('avatar', models.ImageField(blank=True, upload_to='customers/avatars/', verbose_name='Ảnh đại diện')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế')),
                ('business_license', models.CharField(blank=True, max_length=50, verbose_name='Giấy phép kinh doanh')),
                ('representative_name', models.CharField(blank=True, max_length=100, verbose_name='Người đại diện')),
                ('representative_title', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ người đại diện')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], default='medium', max_length=10, verbose_name='Mức ưu tiên')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Hạn mức tín dụng')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='Điều kiện thanh toán')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('first_name', models.CharField(max_length=50, verbose_name='Họ')),
                ('last_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='Tên thường gọi')),
                ('full_name', models.CharField(editable=False, max_length=100, verbose_name='Họ tên đầy đủ')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='CMND/CCCD')),
                ('avatar', models.ImageField(blank=True, upload_to='employees/avatars/', verbose_name='Ảnh đại diện')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Người liên hệ khẩn cấp')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='SĐT người liên hệ khẩn cấp')),
                ('department', models.CharField(choices=[('sales', 'Kinh doanh'), ('warehouse', 'Kho'), ('admin', 'Hành chính'), ('finance', 'Tài chính'), ('it', 'Công nghệ thông tin'), ('hr', 'Nhân sự')], max_length=20, verbose_name='Phòng ban')),
                ('position', models.CharField(choices=[('manager', 'Quản lý'), ('supervisor', 'Giám sát'), ('staff', 'Nhân viên'), ('intern', 'Thực tập sinh')], max_length=20, verbose_name='Chức vụ')),
                ('hire_date', models.DateField(verbose_name='Ngày vào làm')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Lương cơ bản')),
                ('job_description', models.TextField(blank=True, verbose_name='Mô tả công việc')),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'Trung học phổ thông'), ('college', 'Cao đẳng'), ('university', 'Đại học'), ('master', 'Thạc sĩ'), ('doctor', 'Tiến sĩ')], max_length=20, verbose_name='Trình độ học vấn')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Độc thân'), ('married', 'Đã kết hôn'), ('divorced', 'Đã ly hôn')], max_length=20, verbose_name='Tình trạng hôn nhân')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Tên ngân hàng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'ordering': ['-created_at'],
            },
        ),
    ]
