# Generated by Django 4.2.7 on 2025-08-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='business_license',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='representative_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='representative_title',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tax_code',
        ),
    ]
