# Generated by Django 4.2.7 on 2025-08-18 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên kho')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã kho')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sức chứa (tấn)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Quản lý kho')),
            ],
            options={
                'verbose_name': 'Kho',
                'verbose_name_plural': 'Kho',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã kiểm kê')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('in_progress', 'Đang kiểm kê'), ('completed', 'Hoàn thành'), ('cancelled', 'Hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Kiểm kê',
                'verbose_name_plural': 'Kiểm kê',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('inbound', 'Nhập kho'), ('outbound', 'Xuất kho'), ('transfer', 'Chuyển kho'), ('adjustment', 'Điều chỉnh'), ('damaged', 'Hàng hỏng'), ('expired', 'Hàng hết hạn')], max_length=20, verbose_name='Loại biến động')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số lượng')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Đơn giá')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='Loại tham chiếu')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID tham chiếu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Biến động tồn kho',
                'verbose_name_plural': 'Biến động tồn kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTakingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số lượng hệ thống')),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số lượng thực tế')),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chênh lệch')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm')),
                ('stock_taking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.stocktaking')),
            ],
            options={
                'verbose_name': 'Chi tiết kiểm kê',
                'verbose_name_plural': 'Chi tiết kiểm kê',
                'unique_together': {('stock_taking', 'product')},
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số lượng tồn')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số lượng đặt trước')),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mức tồn kho tối thiểu')),
                ('max_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mức tồn kho tối đa')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật cuối')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
