# Generated by Django 4.2.7 on 2025-08-18 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=20, unique=True, verbose_name='Mã khách hàng')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có định dạng: '+999999999'. Tối đa 15 chữ số.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('address', models.TextField(verbose_name='Địa chỉ chi tiết')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Tên công ty')),
                ('tax_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã số thuế')),
                ('business_license', models.CharField(blank=True, max_length=50, verbose_name='Giấy phép kinh doanh')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Tên ngân hàng')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản')),
                ('account_holder', models.CharField(blank=True, max_length=100, verbose_name='Tên chủ tài khoản')),
                ('membership_level', models.CharField(choices=[('bronze', 'Đồng'), ('silver', 'Bạc'), ('gold', 'Vàng'), ('platinum', 'Bạch kim'), ('diamond', 'Kim cương')], default='bronze', max_length=10, verbose_name='Cấp thành viên')),
                ('points', models.IntegerField(default=0, verbose_name='Điểm tích lũy')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Hạn mức tín dụng')),
                ('preferred_products', models.TextField(blank=True, verbose_name='Sản phẩm ưa thích')),
                ('preferred_payment_method', models.CharField(blank=True, max_length=50, verbose_name='Phương thức thanh toán ưa thích')),
                ('preferred_delivery_time', models.CharField(blank=True, max_length=100, verbose_name='Thời gian giao hàng ưa thích')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Tổng số đơn hàng')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng chi tiêu')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá trị đơn hàng trung bình')),
                ('customer_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá khách hàng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('first_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày đặt hàng đầu tiên')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày đặt hàng cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Nhà riêng'), ('office', 'Văn phòng'), ('warehouse', 'Kho hàng'), ('other', 'Khác')], max_length=20, verbose_name='Loại địa chỉ')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=17, verbose_name='Số điện thoại')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('address', models.TextField(verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Địa chỉ khách hàng',
                'verbose_name_plural': 'Địa chỉ khách hàng',
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'CMND/CCCD'), ('business_license', 'Giấy phép kinh doanh'), ('tax_certificate', 'Giấy chứng nhận thuế'), ('contract', 'Hợp đồng'), ('other', 'Khác')], max_length=20, verbose_name='Loại tài liệu')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('file', models.FileField(upload_to='customer_documents/', verbose_name='File tài liệu')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
            ],
            options={
                'verbose_name': 'Tài liệu khách hàng',
                'verbose_name_plural': 'Tài liệu khách hàng',
            },
        ),
        migrations.CreateModel(
            name='CustomerWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='customers.customer')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.cropproduct')),
            ],
            options={
                'verbose_name': 'Danh sách yêu thích',
                'verbose_name_plural': 'Danh sách yêu thích',
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá (1-5 sao)')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề đánh giá')),
                ('content', models.TextField(verbose_name='Nội dung đánh giá')),
                ('product_quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Chất lượng sản phẩm')),
                ('delivery_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Thời gian giao hàng')),
                ('service_quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Chất lượng dịch vụ')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đánh giá đã xác thực')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Đánh giá nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customers.customer')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Đánh giá khách hàng',
                'verbose_name_plural': 'Đánh giá khách hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
