# Generated by Django 4.2.7 on 2025-08-18 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_code', models.CharField(max_length=20, unique=True, verbose_name='Mã nông dân')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nông dân/Tổ chức')),
                ('farmer_type', models.CharField(choices=[('individual', 'Cá nhân'), ('cooperative', 'Hợp tác xã'), ('company', 'Doanh nghiệp')], max_length=20, verbose_name='Loại hình')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có định dạng: '+999999999'. Tối đa 15 chữ số.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('address', models.TextField(verbose_name='Địa chỉ chi tiết')),
                ('farming_region', models.CharField(max_length=200, verbose_name='Vùng canh tác')),
                ('total_farm_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng diện tích canh tác (ha)')),
                ('active_farm_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diện tích đang canh tác (ha)')),
                ('farming_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kinh nghiệm canh tác (năm)')),
                ('main_crops', models.TextField(verbose_name='Cây trồng chính')),
                ('certifications', models.CharField(choices=[('organic', 'Hữu cơ'), ('vietgap', 'VietGAP'), ('globalgap', 'GlobalGAP'), ('haccp', 'HACCP'), ('iso', 'ISO'), ('none', 'Không có')], default='none', max_length=20, verbose_name='Chứng nhận')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Số chứng nhận')),
                ('certification_expiry', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn chứng nhận')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Tên ngân hàng')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản')),
                ('account_holder', models.CharField(blank=True, max_length=100, verbose_name='Tên chủ tài khoản')),
                ('tax_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã số thuế')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Tổng số đánh giá')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nông dân nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Nông dân',
                'verbose_name_plural': 'Nông dân',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200, verbose_name='Tên khu vực')),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diện tích (ha)')),
                ('soil_type', models.CharField(max_length=100, verbose_name='Loại đất')),
                ('water_source', models.CharField(max_length=100, verbose_name='Nguồn nước')),
                ('coordinates', models.CharField(blank=True, max_length=100, verbose_name='Tọa độ GPS')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_areas', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Khu vực canh tác',
                'verbose_name_plural': 'Khu vực canh tác',
            },
        ),
        migrations.CreateModel(
            name='FarmerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'CMND/CCCD'), ('business_license', 'Giấy phép kinh doanh'), ('land_certificate', 'Giấy chứng nhận quyền sử dụng đất'), ('organic_certificate', 'Chứng nhận hữu cơ'), ('vietgap_certificate', 'Chứng nhận VietGAP'), ('globalgap_certificate', 'Chứng nhận GlobalGAP'), ('quality_certificate', 'Chứng nhận chất lượng'), ('other', 'Khác')], max_length=30, verbose_name='Loại tài liệu')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('file', models.FileField(upload_to='farmer_documents/', verbose_name='File tài liệu')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Tài liệu nông dân',
                'verbose_name_plural': 'Tài liệu nông dân',
            },
        ),
        migrations.CreateModel(
            name='CropProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('variety', models.CharField(max_length=100, verbose_name='Giống/Loại')),
                ('planting_date', models.DateField(verbose_name='Ngày gieo trồng')),
                ('harvest_season', models.CharField(choices=[('spring', 'Xuân'), ('summer', 'Hè'), ('autumn', 'Thu'), ('winter', 'Đông'), ('year_round', 'Quanh năm')], max_length=20, verbose_name='Mùa vụ')),
                ('expected_harvest_date', models.DateField(verbose_name='Ngày dự kiến thu hoạch')),
                ('actual_harvest_date', models.DateField(blank=True, null=True, verbose_name='Ngày thu hoạch thực tế')),
                ('estimated_yield', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sản lượng dự kiến (kg)')),
                ('actual_yield', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sản lượng thực tế (kg)')),
                ('quality_grade', models.CharField(choices=[('premium', 'Cao cấp'), ('grade_a', 'Loại A'), ('grade_b', 'Loại B'), ('standard', 'Tiêu chuẩn')], max_length=20, verbose_name='Cấp chất lượng')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá/kg (VND)')),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Số lượng đặt hàng tối thiểu')),
                ('is_organic', models.BooleanField(default=False, verbose_name='Sản phẩm hữu cơ')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Có chứng nhận')),
                ('certificate_type', models.CharField(blank=True, max_length=100, verbose_name='Loại chứng nhận')),
                ('is_available', models.BooleanField(default=True, verbose_name='Có sẵn')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả sản phẩm')),
                ('growing_method', models.TextField(blank=True, verbose_name='Phương pháp canh tác')),
                ('harvest_method', models.TextField(blank=True, verbose_name='Phương pháp thu hoạch')),
                ('storage_method', models.TextField(blank=True, verbose_name='Phương pháp bảo quản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_products', to='farmers.farmer')),
                ('farming_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farmers.farmingarea')),
            ],
            options={
                'verbose_name': 'Sản phẩm nông nghiệp',
                'verbose_name_plural': 'Sản phẩm nông nghiệp',
                'ordering': ['-created_at'],
            },
        ),
    ]
