# Generated by Django 4.2.7 on 2025-08-18 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='active_farm_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diện tích đang canh tác (ha)'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farming_experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kinh nghiệm canh tác (năm)'),
        ),
    ]
