# Generated by Django 4.2.7 on 2025-08-18 05:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0001_initial'),
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Số đơn hàng')),
                ('order_type', models.CharField(choices=[('purchase', 'Mua hàng từ nông dân'), ('sale', 'Bán hàng cho khách hàng'), ('export', 'Xuất khẩu'), ('internal', 'Nội bộ')], max_length=20, verbose_name='Loại đơn hàng')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('picking', 'Đang chuẩn bị hàng'), ('packed', 'Đã đóng gói'), ('shipped', 'Đã giao vận'), ('in_transit', 'Đang vận chuyển'), ('delivered', 'Đã giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('returned', 'Đã trả hàng')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('partial', 'Thanh toán một phần'), ('paid', 'Đã thanh toán'), ('overdue', 'Quá hạn'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', max_length=10, verbose_name='Độ ưu tiên')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Ngày giao dự kiến')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('shipping_contact', models.CharField(blank=True, max_length=100, verbose_name='Người nhận')),
                ('shipping_phone', models.CharField(blank=True, max_length=15, verbose_name='SĐT người nhận')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng tiền hàng')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tiền thuế')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Phí vận chuyển')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Giảm giá')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng cộng')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Số vận đơn')),
                ('estimated_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Trọng lượng dự kiến (kg)')),
                ('actual_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Trọng lượng thực tế (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='Khách hàng')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='farmers.farmer', verbose_name='Nông dân')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_type', models.CharField(choices=[('status_change', 'Thay đổi trạng thái'), ('location_update', 'Cập nhật vị trí'), ('note_added', 'Thêm ghi chú'), ('document_uploaded', 'Tải tài liệu'), ('payment_received', 'Nhận thanh toán'), ('issue_reported', 'Báo cáo vấn đề')], max_length=20, verbose_name='Loại theo dõi')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Vị trí')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Kinh độ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('is_public', models.BooleanField(default=True, verbose_name='Hiển thị công khai')),
                ('is_important', models.BooleanField(default=False, verbose_name='Quan trọng')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Theo dõi đơn hàng',
                'verbose_name_plural': 'Theo dõi đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Trạng thái cũ')),
                ('to_status', models.CharField(max_length=20, verbose_name='Trạng thái mới')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thay đổi')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thay đổi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái',
                'verbose_name_plural': 'Lịch sử trạng thái',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Hợp đồng'), ('invoice', 'Hóa đơn'), ('packing_list', 'Danh sách đóng gói'), ('bill_of_lading', 'Vận đơn'), ('certificate', 'Chứng chỉ'), ('other', 'Khác')], max_length=20, verbose_name='Loại tài liệu')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('file', models.FileField(upload_to='order_documents/', verbose_name='File')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Tài liệu đơn hàng',
                'verbose_name_plural': 'Tài liệu đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Thành tiền')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Thuế suất (%)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Giảm giá (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
