# Generated by Django 4.2.7 on 2025-08-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('purchase', 'Mua hàng từ nông dân'), ('sale', 'Bán hàng cho khách hàng')], max_length=20, verbose_name='Loại đơn hàng'),
        ),
    ]
