# Generated by Django 4.2.7 on 2025-08-18 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã sản phẩm')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('origin', models.CharField(choices=[('domestic', 'Trong nước'), ('imported', 'Nhập khẩu')], max_length=20, verbose_name='Xuất xứ')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='Quốc gia xuất xứ')),
                ('quality_grade', models.CharField(choices=[('A', 'Loại A (Xuất khẩu)'), ('B', 'Loại B (Nội địa cao cấp)'), ('C', 'Loại C (Nội địa thường)')], max_length=5, verbose_name='Phân loại chất lượng')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá vốn')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá bán')),
                ('export_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá xuất khẩu')),
                ('shelf_life_days', models.PositiveIntegerField(verbose_name='Hạn sử dụng (ngày)')),
                ('storage_temperature_min', models.FloatField(blank=True, null=True, verbose_name='Nhiệt độ bảo quản tối thiểu (°C)')),
                ('storage_temperature_max', models.FloatField(blank=True, null=True, verbose_name='Nhiệt độ bảo quản tối đa (°C)')),
                ('humidity_requirement', models.CharField(blank=True, max_length=50, verbose_name='Yêu cầu độ ẩm')),
                ('hs_code', models.CharField(blank=True, max_length=20, verbose_name='Mã HS')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Thuế suất (%)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh chính')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên đơn vị')),
                ('symbol', models.CharField(max_length=10, verbose_name='Ký hiệu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Đơn vị tính',
                'verbose_name_plural': 'Đơn vị tính',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Hình ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('is_main', models.BooleanField(default=False, verbose_name='Hình ảnh chính')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unit', verbose_name='Đơn vị tính'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thông số')),
                ('value', models.CharField(max_length=200, verbose_name='Giá trị')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Đơn vị')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'verbose_name': 'Thông số sản phẩm',
                'verbose_name_plural': 'Thông số sản phẩm',
                'unique_together': {('product', 'name')},
            },
        ),
    ]
